= CSS Introduction
:hp-tags: introduction, css

You've probably been looking at your HTML thinking, "This is flat and boring. Nothing like the crazy diversity I see out on the web."  This, as you may know, is because straight HTML focuses only on the *content* of a document.  To work with document *presentation* we need to introduce https://en.wikipedia.org/wiki/Cascading_Style_Sheets[Cascading Style Sheets] or CSS for short.  This seperation of content and presentation was intentional by the https://en.wikipedia.org/wiki/World_Wide_Web_Consortium[W3C] and allows for a lot of flexibility.  The content can be consumed or used in another way without the extra markup of the presentation polluting it.  Further, the presentation can be altered without worrying about changing the content.  A great illustration of this is the http://www.csszengarden.com/[CSS Zen Garden].  They have a collection of styles that people have done on top of the same bit of HTML.  In other words, on each of these pages ( http://www.csszengarden.com/220/[1], http://www.csszengarden.com/218/[2], http://www.csszengarden.com/215/[3] ) the exact same HTML document is used, the only difference between them is the CSS.  Click through a few of the designs, the visual differences that just a set of CSS instructions can provide is pretty amazing.
