= A Beginning
:hp-tags: environment

I've set aside this small blog space to be a working lesson plan of sorts.  As we progress through a site build, I will post _lessons_ here that will serve as a next step.  Presently we have https://www.pinterest.com/irainsloppyhell/web-design/[a selection of site designs to choose from].  These designs contain complete `.psd` files, and are meant to represent the file you will likely recieve from a designer.  Look them over and when you have made a choice, we will move forward with the work.

=== A few Thoughts on Your Environment

While it is completely possible to develop from a windows machine, I would highly suggest working with OSX (freeBSD), or a linux distribution. http://www.ubuntu.com/[Ubuntu] is probably the easiest to get going with. While this may seem like more work upfront to work with an unfamiliar operating system, it will wind up saving much time in the long run.  Most webservers run on a flavor of linux (redhat or centos usually) and will become immensly useful to familiarize yourself with linux basics early on.

Reguardless of your choice of OS you will need a good text editor.  https://www.sublimetext.com/[Sublime text] is a great choice to begin with.  It goes out of it's way to help out the developer, with auto completion, syntax highlighting, auto closure, and basic document structure checks.  If you are on windows some folks seem to really like http://notepad-plus-plus.org/[notepad++].

It would be a good idea to go ahead and https://github.com/[create a github account], and to install git on your machiene.  We will be using this pretty much from the beginning, and is indespensible knowledge for any developer. _Don't worry if you don't understand it right now, we'll go over that._