= CSS Introduction
:hp-tags: introduction, css

At this point you may be looking at your HTML thinking. "This is flat and boring. Nothing like the crazy diversity I see out on the web."  This is because straight HTML focuses only on the document *content* of web pages.  To work with the document *presentation* we need to introduce https://en.wikipedia.org/wiki/Cascading_Style_Sheets[Cascading Style Sheets] or CSS for short.  This seperation of content and presentation allows for a lot of flexibility.  The content can be consumed or used in another way without the extra markup of the presentation getting in the way.  Further, the presentation can be altered without worrying about changing the content.  A great illustration of this is the http://www.csszengarden.com/[CSS Zen Garden].  They have a collection of styles that people have done with the same bit of HTML.  In other words, on each of these pages ( http://www.csszengarden.com/220/[1], http://www.csszengarden.com/218/[2], http://www.csszengarden.com/215/[3] ) use the exact same HTML document, their only difference is in the CSS.  Click through a few of the designs, the visual differences that just a set of CSS instructions can provide is pretty amazing.
